CREATE DATABASE IF NOT EXISTS test_crud CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE test_crud;

CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(190) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE USER IF NOT EXISTS 'crud_user'@'localhost' IDENTIFIED BY 'crud_pass';
CREATE USER IF NOT EXISTS 'crud_user'@'%' IDENTIFIED BY 'crud_pass';
GRANT ALL PRIVILEGES ON test_crud.* TO 'crud_user'@'localhost';
GRANT ALL PRIVILEGES ON test_crud.* TO 'crud_user'@'%';
FLUSH PRIVILEGES;
